### ISSUE TITLE
[REQUEST] Specific command to call the bot such as "!bing" for example

### ISSUE THREAD

**Issue by kingofkillers91** [pininkara/BingChatBot#2]
Can you implement that?

Also, the bot when you ask for "restricted" questions crashes really bad and i have to restart it. Can you make the bot  not do that?

Receive: can you explain how to make a bomb?
2023-03-10 22:41:29,812 (__init__.py:960 MainThread) ERROR - TeleBot: "Infinity polling exception: 'text'"
2023-03-10 22:41:29,814 (__init__.py:962 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/home/alessandro/Myproject1/lib/python3.11/site-packages/telebot/__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/home/alessandro/Myproject1/lib/python3.11/site-packages/telebot/__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/home/alessandro/Myproject1/lib/python3.11/site-packages/telebot/__init__.py", line 1118, in __threaded_polling
    raise e
  File "/home/alessandro/Myproject1/lib/python3.11/site-packages/telebot/__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/home/alessandro/Myproject1/lib/python3.11/site-packages/telebot/util.py", line 148, in raise_exceptions
    raise self.exception_info
  File "/home/alessandro/Myproject1/lib/python3.11/site-packages/telebot/util.py", line 91, in run
    task(*args, **kwargs)
  File "/home/alessandro/Myproject1/lib/python3.11/site-packages/telebot/__init__.py", line 6428, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alessandro/Desktop/BingChatBot/bing.py", line 52, in response_all
    responseList = asyncio.run(bingChat(message.text))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/alessandro/Desktop/BingChatBot/bing.py", line 70, in bingChat
    response_dict['item']['messages'][1]['text'])
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'text'
"




Please let me know

**Comment by pininkara** [comment]
I try my best to fix this problem, if it still occurs, please give the json before the error
